### 데이터 정리 및 최종 확인

##### 전처리 및 가공된 데이터들을 읽기

In [1]:
import pandas as pd

criminalArea = pd.read_csv('./data/criminalArea.csv')
criminalPlace = pd.read_csv('./data/criminalPlace.csv')
criminalTime = pd.read_csv('./data/criminalTime.csv')
criminalDay = pd.read_csv('./data/criminalDay.csv')

##### 시각화를 위한 데이터 정리 - criminalArea

In [11]:
print(f'데이터 크기 : {criminalArea.shape}')
print(f'데이터 칼럼 : {list(criminalArea.columns)}')
print('범죄 종류 :', list(criminalArea['범죄중분류']))
criminalAreaTop10 = criminalArea.loc[:10, list(criminalArea.columns)[:10+1]]
criminalAreaTop10

데이터 크기 : (35, 87)
데이터 칼럼 : ['범죄중분류', '서울', '부산', '대구', '인천', '광주', '대전', '경기 수원', '울산', '경남 창원', '경기 부천', '경기 안산', '경기 고양', '경기 성남', '충북 청주', '제주 제주', '충남 천안', '경기 용인', '경남 김해', '경기 평택', '전북 전주', '경기 시흥', '경북 구미', '경북 포항', '경기 안양', '경기 화성', '경기 남양주', '경기 의정부', '경기 파주', '강원 원주', '전남 목포', '전남 여수', '경남 거제', '전남 순천', '경남 진주', '강원 춘천', '경북 경주', '경기 광주', '전북 군산', '경기 광명', '경기 김포', '경남 양산', '전북 익산', '충남 아산', '충북 충주', '제주 서귀포', '경기 구리', '경북 경산', '강원 강릉', '경기 오산', '경기 군포', '경기 양주', '경기 포천', '경기 이천', '경기 안성', '경남 통영', '충남 당진', '경북 안동', '경기 하남', '전남 광양', '충남 서산', '경남 사천', '경북 김천', '충남 보령', '충북 제천', '경기 여주', '강원 속초', '충남 논산', '경기 의왕', '강원 동해', '세종', '전북 정읍', '경기 동두천', '경북 영주', '경북 영천', '경남 밀양', '충남 공주', '경북 상주', '전북 김제', '강원 삼척', '전북 남원', '경북 문경', '경기 과천', '강원 태백', '전남 나주', '충남 계룡', '경남 마산']
범죄 종류 : ['교통범죄', '절도', '사기', '폭행', '특별경제범죄', '손괴', '횡령', '상해', '폭력행위등', '병역범죄', '성풍속범죄', '강제추행', '보건범죄', '문서인장', '협박', '도박범죄', '마약범죄', '강간', '배임', '공갈', '환경범죄', '통화', '방화', '강도', '노동범죄', '체포감금', '살인미수등', '선거범죄', '유사강간', '직무유기', '직권남용', '살인기수', '유가증권인지', '증수뢰', '안보범죄']

,범죄중분류,서울,부산,대구,인천,광주,대전,경기 수원,울산,경남 창원,경기 부천
0,교통범죄,74958,35841,39725,31163,23412,13556,14715,16600,12650,10467
1,절도,55280,20136,12759,10679,8438,9495,6487,5449,5860,5048
2,사기,53879,20533,11507,13141,7669,7250,5749,5606,6170,5727
3,폭행,36904,8852,6607,9774,5386,4054,4123,4213,2650,3129
4,특별경제범죄,22075,13868,3421,5751,2535,1635,1596,1289,1018,1449
5,손괴,11735,3639,3019,3365,1791,1804,1497,1530,1199,1158
6,횡령,13314,2980,1725,2763,1416,1216,1231,794,708,1084
7,상해,7174,4675,2736,2179,1162,1516,938,1353,1187,524
8,폭력행위등,6725,2449,1595,1988,817,1045,1101,906,669,591
9,병역범죄,4591,959,800,1200,371,630,433,382,355,355
10,성풍속범죄,5421,1164,933,1190,376,438,368,257,164,360

##### 시각화를 위한 데이터 정리 - criminalPlace

In [15]:
print(f'데이터 크기 : {criminalPlace.shape}')
print(f'데이터 칼럼 : {list(criminalPlace.columns)}')
print('범죄 종류 :', list(criminalPlace['범죄중분류']))
criminalPlaceTop10 = criminalPlace.loc[:10, list(criminalPlace.columns)[:10+1]]
criminalPlaceTop10

데이터 크기 : (35, 33)
데이터 칼럼 : ['범죄중분류', '노상', '아파트', '사무실', '단독주택', '유흥업소', '상점', '주차장', '숙박업소 및 목욕탕', '편의점', '슈퍼마켓', '시장_노점', '의료기관', '고속도로', '산야', '금융기관', '공장', '역_대합실', '유원지', '공사장_광산', '대형할인매장', '학교', '공중화장실', '지하철', '백화점', '피씨방', '창고', '종교기관', '흥행장', '해상', '부대', '공지', '구금장소']
범죄 종류 : ['교통범죄', '절도', '사기', '폭행', '손괴', '횡령', '상해', '특별경제범죄', '협박', '보건범죄', '강제추행', '성풍속범죄', '마약범죄', '문서인장', '폭력행위등', '강간', '도박범죄', '환경범죄', '배임', '공갈', '방화', '체포감금', '병역범죄', '유사강간', '직무유기', '직권남용', '강도', '살인미수등', '통화', '노동범죄', '살인기수', '선거범죄', '증수뢰', '안보범죄', '유가증권인지']

,범죄중분류,노상,아파트,사무실,단독주택,유흥업소,상점,주차장,숙박업소 및 목욕탕,편의점,슈퍼마켓
0,교통범죄,300530,105,74,38,14,36,769,7,4,1
1,절도,46374,16482,2282,8535,7116,15031,9891,2666,6143,9920
2,사기,44667,10071,28142,12618,11025,4370,1326,1153,2389,354
3,폭행,41284,23656,2946,12716,9270,1506,2850,1903,1365,526
4,손괴,20560,8144,735,4452,2216,875,7254,2157,268,118
5,횡령,20347,2016,3926,744,1020,1516,952,197,1013,658
6,상해,9761,4876,1049,3014,3378,347,626,696,157,90
7,특별경제범죄,4104,1278,5978,874,4825,2187,187,604,1381,373
8,협박,6111,5052,693,3338,1134,281,265,195,208,54
9,보건범죄,919,1426,841,874,5865,780,15,164,52,59
10,강제추행,2602,1761,608,1096,1865,378,98,803,226,117

##### 시각화를 위한 데이터 정리 - criminalTime

In [14]:
print(f'데이터 크기 : {criminalTime.shape}')
print(f'데이터 칼럼 : {list(criminalTime.columns)}')
print('범죄 종류 :', list(criminalTime['범죄중분류']))
criminalTimeTop10 = criminalTime.loc[:10, list(criminalTime.columns)[:10+1]]
criminalTimeTop10

데이터 크기 : (35, 9)
데이터 칼럼 : ['범죄중분류', '21:00 ~ 23:59', '18:00 ~ 20:59', '15:00 ~ 17:59', '09:00 ~ 11:59', '12:00 ~ 14:59', '0:00 ~ 02:59', '06:00 ~ 08:59', '03:00 ~ 05:59']
범죄 종류 : ['교통범죄', '절도', '폭행', '사기', '손괴', '횡령', '상해', '특별경제범죄', '협박', '강제추행', '성풍속범죄', '폭력행위등', '보건범죄', '마약범죄', '강간', '도박범죄', '문서인장', '공갈', '병역범죄', '배임', '환경범죄', '방화', '체포감금', '강도', '노동범죄', '유사강간', '통화', '살인미수등', '직권남용', '선거범죄', '살인기수', '직무유기', '유가증권인지', '증수뢰', '안보범죄']

,범죄중분류,21:00 ~ 23:59,18:00 ~ 20:59,15:00 ~ 17:59,09:00 ~ 11:59,12:00 ~ 14:59,0:00 ~ 02:59,06:00 ~ 08:59,03:00 ~ 05:59
0,교통범죄,70537,58164,53506,44265,45675,24513,37189,23438
1,절도,20568,27229,28553,21501,27167,13088,13094,14167
2,폭행,34120,20704,14791,11591,12509,19226,9345,16377
3,사기,12387,13930,21648,39184,30405,5443,3056,3949
4,손괴,10822,9323,6289,5277,4983,5107,4014,4556
5,횡령,6367,6646,6584,6781,6586,2754,2780,2526
6,상해,7433,4585,3684,2967,3025,4166,2247,3408
7,특별경제범죄,4320,3768,4802,6702,5340,1688,1333,1426
8,협박,3437,3304,2687,2288,2251,1316,1339,1036
9,강제추행,2901,2189,1706,1163,1300,1855,1293,1921
10,성풍속범죄,1931,1675,1724,1126,1225,736,773,597

##### 시각화를 위한 데이터 정리 - criminalDay

In [13]:
print(f'데이터 크기 : {criminalDay.shape}')
print(f'데이터 칼럼 : {list(criminalDay.columns)}')
print('범죄 종류 :', list(criminalDay['범죄중분류']))
criminalDayTop10 = criminalDay.loc[:10, list(criminalDay.columns)[:10+1]]
criminalDayTop10

데이터 크기 : (35, 8)
데이터 칼럼 : ['범죄중분류', '금요일', '목요일', '화요일', '수요일', '월요일', '토요일', '일요일']
범죄 종류 : ['교통범죄', '사기', '절도', '폭행', '횡령', '손괴', '특별경제범죄', '상해', '협박', '강제추행', '성풍속범죄', '병역범죄', '보건범죄', '문서인장', '폭력행위등', '마약범죄', '도박범죄', '강간', '공갈', '배임', '환경범죄', '방화', '체포감금', '통화', '노동범죄', '강도', '유사강간', '직권남용', '선거범죄', '직무유기', '살인미수등', '살인기수', '증수뢰', '안보범죄', '유가증권인지']

     범죄중분류    금요일    목요일    화요일    수요일    월요일    토요일    일요일
0     교통범죄  58103  54846  53605  54509  51459  57134  47698
1       사기  52039  51654  51876  51225  52740  24124  20814
2       절도  28156  26098  25671  26061  26239  29266  25466
3       폭행  22045  21080  20766  20981  19966  26494  25865
4       횡령   9317   8460   8128   8318   8559   8495   7231
5       손괴   8788   7989   7634   7766   7974   9378   8617
6   특별경제범죄   8502   8432   8608   8477   8724   4709   3948
7       상해   5270   5110   5063   5038   4908   5776   5693
8       협박   3040   2961   3039   3072   3013   3011   2886
9     강제추행   2542   2231   2306   2358   2272   2831   2580
10   성풍속범죄   1982   1900   1956   2066   1957   1670   1614