In [4]:
import pandas as pd

criminalTimeAndDay = pd.read_csv('criminalTimeAndDay.csv')
criminalTimeAndDay.head()

,범죄중분류,0시00분-02시59분,03시00분-05시59분,06시00분-08시59분,09시00분-11시59분,12시00분-14시59분,15시00분-17시59분,18시00분-20시59분,21시00분-23시59분,미상,일,월,화,수,목,금,토
0,살인기수,15,21,20,28,38,33,43,49,50,38,45,48,40,37,49,40
1,살인미수등,33,50,29,44,46,60,66,82,72,71,70,68,62,73,85,53
2,강도,105,131,44,59,68,72,81,107,131,111,113,116,105,124,121,108
3,강간,630,885,417,293,325,311,425,719,1305,869,686,734,719,682,722,898
4,유사강간,102,110,57,62,60,55,66,89,181,145,99,109,92,89,112,136