In [1]:
import pandas as pd

criminalPlace = pd.read_csv('criminalPlace.csv')
criminalPlace.head()

,범죄중분류,아파트_연립다세대,단독주택,고속도로,노상,백화점,슈퍼마켓,편의점,대형할인매장,상점,...,종교기관,산야,해상,부대,구금장소,공지,주차장,공중화장실,피씨방,기타
0,살인기수,92,57,1,43,0,0,0,0,0,...,0,2,1,0,0,0,2,0,1,19
1,살인미수등,116,67,1,87,0,3,3,0,3,...,1,2,0,0,0,0,7,1,0,28
2,강도,78,47,1,114,2,10,39,3,32,...,1,4,0,0,0,0,10,3,1,36
3,강간,1561,976,2,127,0,0,1,0,33,...,8,8,0,1,0,1,20,43,4,377
4,유사강간,247,147,0,36,0,0,2,0,10,...,2,1,0,0,1,0,11,9,1,60